-- AlterTable
ALTER TABLE `Chat` MODIFY `updatedAt` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);

-- AlterTable
ALTER TABLE `Message` MODIFY `updatedAt` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);

-- AlterTable
ALTER TABLE `User` MODIFY `updatedAt` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
